// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: hello-server/pb/hello.proto

package hello_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int64                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_hello_server_pb_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_server_pb_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_hello_server_pb_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_hello_server_pb_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_server_pb_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_hello_server_pb_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_hello_server_pb_hello_proto protoreflect.FileDescriptor

const file_hello_server_pb_hello_proto_rawDesc = "" +
	"\n" +
	"\x1bhello-server/pb/hello.proto\x12\x02pb\"4\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x03R\x03age\"!\n" +
	"\rHelloResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2w\n" +
	"\aGreeter\x121\n" +
	"\bSayHello\x12\x10.pb.HelloRequest\x1a\x11.pb.HelloResponse\"\x00\x129\n" +
	"\x0eLotsOfSayHello\x12\x10.pb.HelloRequest\x1a\x11.pb.HelloResponse\"\x000\x01B\x1bZ\x19hello-server/hello_serverb\x06proto3"

var (
	file_hello_server_pb_hello_proto_rawDescOnce sync.Once
	file_hello_server_pb_hello_proto_rawDescData []byte
)

func file_hello_server_pb_hello_proto_rawDescGZIP() []byte {
	file_hello_server_pb_hello_proto_rawDescOnce.Do(func() {
		file_hello_server_pb_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_server_pb_hello_proto_rawDesc), len(file_hello_server_pb_hello_proto_rawDesc)))
	})
	return file_hello_server_pb_hello_proto_rawDescData
}

var file_hello_server_pb_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_server_pb_hello_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: pb.HelloRequest
	(*HelloResponse)(nil), // 1: pb.HelloResponse
}
var file_hello_server_pb_hello_proto_depIdxs = []int32{
	0, // 0: pb.Greeter.SayHello:input_type -> pb.HelloRequest
	0, // 1: pb.Greeter.LotsOfSayHello:input_type -> pb.HelloRequest
	1, // 2: pb.Greeter.SayHello:output_type -> pb.HelloResponse
	1, // 3: pb.Greeter.LotsOfSayHello:output_type -> pb.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_server_pb_hello_proto_init() }
func file_hello_server_pb_hello_proto_init() {
	if File_hello_server_pb_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_server_pb_hello_proto_rawDesc), len(file_hello_server_pb_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_server_pb_hello_proto_goTypes,
		DependencyIndexes: file_hello_server_pb_hello_proto_depIdxs,
		MessageInfos:      file_hello_server_pb_hello_proto_msgTypes,
	}.Build()
	File_hello_server_pb_hello_proto = out.File
	file_hello_server_pb_hello_proto_goTypes = nil
	file_hello_server_pb_hello_proto_depIdxs = nil
}
